name: creditcard
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/cartoes.json
    - assets/visa.png
    - assets/mastercard.png
    - assets/default.png
    - assets/4111111111111111.json
    - assets/5500000000000004.json
    - assets/4012888888881881.json
    - assets/5555555555554444.json


  fonts:
    - family: Rawline
      fonts:
        - asset: assets/fonts/rawline/rawline-100.ttf
          weight: 100
        - asset: assets/fonts/rawline/rawline-100i.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/rawline/rawline-200.ttf
          weight: 200
        - asset: assets/fonts/rawline/rawline-200i.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/rawline/rawline-300.ttf
          weight: 300
        - asset: assets/fonts/rawline/rawline-300i.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/rawline/rawline-400.ttf
          weight: 400
        - asset: assets/fonts/rawline/rawline-400i.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/rawline/rawline-500.ttf
          weight: 500
        - asset: assets/fonts/rawline/rawline-500i.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/rawline/rawline-600.ttf
          weight: 600
        - asset: assets/fonts/rawline/rawline-600i.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/rawline/rawline-700.ttf
          weight: 700
        - asset: assets/fonts/rawline/rawline-700i.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/rawline/rawline-800.ttf
          weight: 800
        - asset: assets/fonts/rawline/rawline-800i.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/rawline/rawline-900.ttf
          weight: 900
        - asset: assets/fonts/rawline/rawline-900i.ttf
          weight: 900
          style: italic


